---
version: '3.1'
services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - "./scripts/mysql-init.sql:/docker-entrypoint-initdb.d/1.sql"
    ports:
      - 3306

  food:
    build: .
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASS=example
    env_file:
      - .food.env
    links:
      - "db:db"
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

