#!/bin/bash

source .food.env

DATABASE_HOST=127.0.0.1 DATABASE_PORT=$DATABASE_PORT \
  DATABASE_USER=$DATABASE_USER DATABASE_PASS=$DATABASE_PASS \
  DATABASE_NAME=$DATABASE_NAME \
  EMAIL_HOST=$EMAIL_HOST EMAIL_PORT=$EMAIL_PORT EMAIL_ACCOUNT=$EMAIL_ACCOUNT \
  EMAIL_RECIPIENTS=$EMAIL_RECIPIENTS EMAIL_PASS=$EMAIL_PASS \
  go run ./cmd/food-cli/main.go "$*"
